linuxdeepin/dtkgui

.release.json, src/src.pro, tools/deepin-gui-settings/deepin-gui-settings.pro
=> chore: remove create dtkgui_config.h codes

src/kernel/dguiapplicationhelper.cpp
旧版控制中心有使用不同的 key 再次调用 setSingleInstance
本次修改后，同一个进程多次调用接口使用后调用的key来锁定文件，符合
之前的 local server close 再 listen 的逻辑。
Influence: dcc setSingleInstance twice
Log: 修复dtkgui升级后dcc无法启动的问题
Change-Id: I97d9146be88d34cc12d16fc75cd1eccdeb53c315
=> fix: dcc 再次调用 setSingleInstance后无法启动

src/kernel/dplatformhandle.cpp
if user has set windowradius, we do not set again when
DPlatformTheme::windowRadiusChanged emit.
Bug: https://pms.uniontech.com/bug-view-147219.html
Log: fix dock radius changed when set global windowradius
Influence: dock radius
Change-Id: Iba8226a67bbc5dfdac4151ab046725b3b1dca512
=> fix: dock radius changed when set global windowradius

CMakeLists.txt, debian/rules, doc/CMakeLists.txt, src/filedrag/dfiledrag.cpp, src/filedrag/dfiledragserver.cpp
追加基于 doxygen 的文档构建
Related: https://github.com/linuxdeepin/dtkcore/pull/71 https://github.com/linuxdeepin/dtkwidget/pull/121 https://github.com/linuxdeepin/dtkdeclarative/pull/20
=> chore: build doxygen documentation

README.md, README_zh_CN.md
Add zh_CN README.
Log: Add zh_CN README
Influence: None
=> chore: Add zh_CN README

src/kernel/dguiapplicationhelper.cpp
When migrating dtkwidget code, not all code was added
completely, leaving out how to get services through the
other thread.
Log:
Influence: None
Change-Id: Ib45b596bff68a138df0b0dd50d8fb8ec0c3827c4
=> fix: blocked UI when help service is not open

.reuse/dep5
=> chore: update .dep5

src/util/ddciicon.cpp
The AA_UseHighDpiPixmaps attribute is used to control the icon
blurring problem of the high-resolution screen. However, we do
not use this attribute, but expand the standard size of the icon
by default. This is unreasonable. Therefore, we modified the way
to enlarge the icon size to use AA_ After the usehighdpipixmaps
attribute, the icon blurring problem of the high-resolution screen
is solved.
Log:
Change-Id: Ie7d476cdec6c2ddea0a6432bc4a8a7d26aab5cac
=> fix: Abnormal Dci Icon on high resolution screen

CMakeLists.txt
修复错误的 option() 用法
Log: wrong option usage
=> fix: wrong option() usage in CMakeLists.txt

tests/test-recoverage.sh
Now the configure file is cmake , then the shell should be cmake too
Log: fix recoveryshell
=> fix(shell): fix recoveryshell to cmake

LICENSE, README.md, README.zh_CN.md
README and LICENSE
Log: fix licence
=> fix(licence): licence

src/kernel/dguiapplicationhelper.cpp
find dman from system environment variables
Log: none
=> fix: cannot find dman if the installation path not /usr/bin

include/DtkGui/DIcon, include/util/dicon.h, src/util/dicon.cpp, tests/main.cpp, tests/src/ut_dicon.cpp
get pixmap of specified devicePixelRatio
Fix https://pms.uniontech.com/bug-view-162771.html
Log: none
Change-Id: I38b16c8402be74d1ef216faf7c77fa096282dadc
=> feat: add DIcon

src/util/dsvgrenderer.cpp
librsvg2 对 SVG2 的 href 解析有问题，需要改成 xlink:href 规避
当前是临时规避方案，如果后续 librsvg2 升级修复这个问题，可以 revert
https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGURIReference
Task: https://pms.uniontech.com/task-view-218689.html
Influence: 包含href的svg图标
Log: 修复包含href的svg图标无法显示的问题
Change-Id: Idaf0ca9519153cd8fe217aeaaeab250b18f35393
=> fix: 包含 href 特性的 svg 图标无法显示

include/util/ddciiconpalette.h, src/util/ddciiconpalette.cpp
add a way to construct DDciIconPalette from QPalette
Log: none
Change-Id: I4e9b9f8bf3a653c066bf92c7ba1a3ef72526e2ac
=> feat: construct DDciIconPalette from QPalette

src/kernel/dguiapplicationhelper.cpp
1. use asyncCall instead of call to prevent block gui
2. check sessionBus isConnected instead of isServiceRegistered
Log: none
Change-Id: Idac86416735482269d81432aba2993ceceb5e0e5
=> chore: use asyncCall instead of call

examples/CMakeLists.txt, examples/frameless-window/CMakeLists.txt, examples/frameless-window/main.cpp
Show the frameless window implementation.
Log: none
=> feat: add an example

src/kernel/dguiapplicationhelper.cpp
no return value after asyncCall
Log: undefined behavior
Change-Id: I15a6aec8a8ab57e446f25fbf91c979acde667903
=> fix: no return value on some case

examples/frameless-window/main.cpp
Add examples for _d_buildNativeSettings platform function.
Log: none
=> feat: using native settings in frameless window example

.reuse/dep5, tools/CMakeLists.txt, tools/dci-icon-theme/CMakeLists.txt, tools/dci-icon-theme/README.md, tools/dci-icon-theme/main.cpp
add dci-icon-theme tool to generate dci icon theme
Log: none
Influence: dci icon theme
Change-Id: Iec3b6ab5adef6ca2510e2d22bbd78ae7395c7e51
=> feat: add dci-icon-theme tool

.gitignore, docs/util/ddciicon.zh_CN.dox, docs/util/ddciiconpalette.zh_CN.dox, docs/util/index.zh_CN.md
=> docs: add dci docs

.gitignore
=> chore: add gitignore item

src/util/ddciicon.cpp
return DDciIcon(fileName) if fileName is full path
Log: none
Change-Id: I6835074c48792877dfb06842402546d7d428fa6c
=> chore: DDciIcon::fromTheme support absolutePath

docs/CMakeLists.txt
在打开build theme编译选项时会自动下载主题
Log:
=> docs: add doxygen theme

tools/dci-icon-theme/CMakeLists.txt, tools/dci-icon-theme/main.cpp
dci-icon-theme --find deb
"deb" [ "xxx-icon" ]: "/usr/share/dsg/icons/xxx-icon/deb.dci"
Log: none
Change-Id: Ide152e0ba1cba0fb0252ead7304c255a2c0695d4
=> feat: add icon finder for dci-icon-theme

tools/dci-icon-theme/main.cpp
quility of dci icon scaled image
the higher the quality, the larger the dci icon file size
Log: quality option
Change-Id: Ifdfa51091bb560ad76881366a9c5168daf6cc9ab
=> feat: add quality option

misc/DtkGuiConfig.cmake.in, src/CMakeLists.txt
Add dependency of Qt5Gui cause dtkgui depends it.
Log: add find_dependency(Qt5Gui)
=> fix: lost dependency of Qt5Gui

tools/dci-icon-theme/main.cpp
1. update version to 0.0.3
2. fix initQuality not init if --quality not set
Log: none
Change-Id: I66f2d494f9e34194ffed17564334b3e29109737a
=> chore: dci-icon-theme tweak

archlinux/PKGBUILD
Dependiencies not plugin and hard link to library should not mark as optdepends
Log: fix PKGBUILD
=> chore: fix PKGBUILD

docs/util/index.zh_CN.md
Correct markdown title level to fix qch generate error.
Log: fix qch generate error
=> fix: qch generate error

CMakeLists.txt, archlinux/PKGBUILD, src/util/dsvgrenderer.cpp, src/util/util.cmake
1. add DTK_DISABLE_LIBRSVG build option to disable librsvg
2. archlinux DTK_DISABLE_LIBRSVG=ON by default
3. use QSvgRenderer instead of librsvg if option on
Log: archlinux build
=> chore: update archlinux build

tools/dci-icon-theme/main.cpp
Correct a typo in dci-icon-theme/main.cpp
=> chore: correct a typo in dci-icon-theme/main.cpp

tools/dci-icon-theme/README.md, tools/dci-icon-theme/main.cpp
update readme and usage
Log: none
Change-Id: Ibf40852aaa8aca2d21f51fdc37657fc79fd33966
=> chore: update readme and help message

CMakeLists.txt, misc/org.deepin.dtk.ui.preference.json
=> feat: add config file

CMakeLists.txt, debian/libdtkgui5.install, src/CMakeLists.txt
1. move `dconfig_meta_files` to src/CMakeLists.txt
2. add to debian install files
=> chore: install meta file

src/kernel/dguiapplicationhelper.cpp
modify six palette color values both light theme and dark theme, repectively.
Log: adjust palette color values
Issue: #142
=> chore: adjust palette color values

src/kernel/dguiapplicationhelper.cpp
add DDE env support
Issue: https://github.com/linuxdeepin/dtkcore/issues/301
=> chore: IsDeepinEnvironment support DDE

include/kernel/dguiapplicationhelper.h, misc/org.deepin.dtk.ui.preference.json, src/kernel/dguiapplicationhelper.cpp
保存主题功能让非 widget 应用也能用上
Log: 
Change-Id: I9e6673c0e78c25dfc7445623a93189f89cf2c076
=> feat: add setAutoSaveApplciationTheme function

.reuse/dep5
=>  fix reuse

src/kernel/dguiapplicationhelper.cpp
1. dconfig meta file installed by libdtkdata.
2. appid switch to org.deepin.dtk.preference
=> chore: update dconfig appid

src/util/private/dbuiltiniconengine.cpp, src/util/private/dbuiltiniconengine_p.h
add the difference about builtiniconengine from qt5integration
Log: add the difference about builtiniconengine from qt5integration
=> chore: adjust builtiniconengine

src/util/private/xdgiconproxyengine.cpp, src/util/private/xdgiconproxyengine_p.h
add difference about xdgiconproxyengine from qt5integration
Log: add difference about xdgiconproxyengine from qt5integration
=> chore: adjust xdgiconproxyengine

.reuse/dep5, tests/actions/icon_Layout_16px.svg, tests/res.qrc, tests/src/ut_builtinengine.cpp
add unit test ut_builtinengine about builtinengine
Log: add unit test about builtinengine
=> chore: add unit test about builtinengine

include/kernel/dguiapplicationhelper.h, include/kernel/dpalette.h, include/kernel/dplatformtheme.h, src/kernel/dguiapplicationhelper.cpp, src/kernel/dplatformhandle.cpp, src/kernel/dplatformtheme.cpp, tests/src/ut_dplatformtheme.cpp
- DGuiApplicationHelper -7
- DPalette -1
- DPlatformTheme -27 properties
=> refactor!: deprecate some interfaces in dtk6

src/util/private/dciiconengine.cpp, src/util/private/dciiconengine_p.h, src/util/util.cmake
add dciiconengine frome qt5integration
Log: add dciiconengine
=> chore: add dciiconengine

include/util/dicontheme.h, src/util/dicontheme.cpp
dciiconEngine is added to createIconEngine interface.
Log: dciiconEngine is added to createIconEngine interface.
=> chore: adjust icontheme

src/kernel/dforeignwindow.cpp, src/kernel/dguiapplicationhelper.cpp, src/kernel/dplatformhandle.cpp, src/kernel/dregionmonitor.cpp, src/kernel/dwindowgroupleader.cpp, src/kernel/dwindowmanagerhelper.cpp
解决赋值返回警告
Issue: https://github.com/linuxdeepin/dtk/issues/96
=> chore: reduce compilation warnings

src/util/dicontheme.cpp, src/util/private/diconproxyengine.cpp, src/util/private/diconproxyengine_p.h, src/util/util.cmake
add proxyiconengine from qt5integration
Log: add proxyicnengine from qt5integration
=> chore: add proxyiconengine

src/util/private/diconproxyengine.cpp, src/util/util.cmake
adjust some about iconproxyengine to build qt6
Log: fix build failed in qt6 due to proxyengine
=> fix: build failed in qt6 due to proxyengine

docs/util/dicontheme.zh_CN.dox, include/util/dicontheme.h, src/util/dicontheme.cpp
support fallback icon
替换 QIcon：：FromTheme 时很有用
=> feat: DIconTheme::findQIcon add fallback icon

include/util/dicon.h, src/util/dicon.cpp
Add loadNxPixmap for high dpi pixmap.
Log: add loadNxPixmap
=> feat: add helper for high dpi pixmap

include/kernel/dguiapplicationhelper.h, src/kernel/dguiapplicationhelper.cpp, tests/src/ut_dguiapplicationhelper.cpp
- interface: DGuiApplicationHelper::loadTranslator();
- auto load qt_xxx.qm && qtbase_xxx.qm && appName_xxx.qm
- add loadTranslator ut
=> feat: load app and qt Translation files

src/util/private/diconproxyengine.cpp, src/util/private/xdgiconproxyengine.cpp, src/util/private/xdgiconproxyengine_p.h, tests/CMakeLists.txt, tests/images/deepin/cs_rect_64.svg, tests/images/deepin/index.theme, tests/res.qrc, tests/src/ut_diconproxyengine.cpp, tests/src/ut_xdgiconproxyengine.cpp
- forward declaration XdgIconLoaderEngine
- xdgiconloader headers position tweak
- XDG colorScheme color support alpha (css color is RGBA not ARGB)
- add ut_XdgIconProxyEngine ut_DIconProxyEngine
=> chore: iconengine tweak and uint test

tests/CMakeLists.txt, tests/main.cpp, tests/platform-plugin-test/CMakeLists.txt, tests/platform-plugin-test/ddynamicmetaobject.cpp, tests/platform-plugin-test/ddynamicmetaobject.h, tests/platform-plugin-test/dplatformnativeinterface.cpp, tests/platform-plugin-test/dplatformnativeinterface.h, tests/platform-plugin-test/dplatformsettings.cpp, tests/platform-plugin-test/dplatformsettings.h, tests/platform-plugin-test/dummysettings.cpp, tests/platform-plugin-test/dummysettings.h, tests/platform-plugin-test/main.cpp, tests/platform-plugin-test/minimal.json, tests/platform-plugin-test/qminimalbackingstore.cpp, tests/platform-plugin-test/qminimalbackingstore.h, tests/platform-plugin-test/qminimalintegration.cpp, tests/platform-plugin-test/qminimalintegration.h, tests/src/ut_ddciiconpalette.cpp, tests/src/ut_dfiledrag.cpp, tests/src/ut_dnativesettings.cpp, tests/src/ut_dplatformtheme.cpp, tests/src/ut_dwindowmanagerhelper.cpp, tests/test.h
- use QWidget::createWinId instead of QWidget::show  to create window handle(QWindow)
- make tests/test-recoverage.sh runable again
- DDciIconPalette
- DNativeSettings
- add a minimal qpa plugin for test
=> Add some ut

docs/src/dguiapplicationhelper.zh_CN.dox, include/kernel/dguiapplicationhelper.h, src/kernel/dguiapplicationhelper.cpp, src/util/ddciicon.cpp, tests/src/ut_dfiledrag.cpp
1.porting dbus interface(ManualExists) implementation to dtk
Log: rewrite hasUserManual function
=> refactor: rewrite hasUserManual function

dtkgui.cmake, src/CMakeLists.txt, tests/CMakeLists.txt, tests/src/ut_builtinengine.cpp, tests/src/ut_dfiledrag.cpp, tests/src/ut_xdgiconproxyengine.cpp, tests/test-recoverage.sh
- filedrag destroy server to emit serverDestroyed
- compare color sometime failed, convert to rgb first
- ut build without source(cmake -DEnableCov=ON)
=> chore: ut build without source

debian/control
=> chore: add DtkBuildHelper depends

tests/platform-plugin-test/CMakeLists.txt, tests/src/ut_builtinengine.cpp, tests/src/ut_dplatformtheme.cpp
=> fix(build): ut failed on Qt6.4

src/util/dicontheme.cpp
=> fix: when iconName is absolute path

src/kernel/dplatformhandle.cpp
it reports `unique connections require a pointer to member
function of a QObject subclass` for UniqueConnection.
=> chore: warning for connect

src/kernel/dguiapplicationhelper.cpp
ApplicationPaletteChange more times.
=> fix: app refresh slowly

include/kernel/dguiapplicationhelper.h, src/kernel/dguiapplicationhelper.cpp
get the specified type of palette.
=> feat: support not following changes in application themes

include/util/dicontheme.h, src/util/dicontheme.cpp, src/util/private/diconproxyengine.cpp
- if flag is set always try create iconengine
- avoid too much logs
- insert to cache when icon is not null
=> create engine again if engine is null

tools/dci-icon-theme/main.cpp
- add error log(callback)
- support multiple size
- update version to 0.0.5
e.g.
```
ls /usr/share/icons/vintage/apps
128  16  24  32  48  64  96
dci-icon-theme /usr/share/icons/vintage/apps -o /tmp/dcis/vintage -O 3=98
dci --tree /tmp/vintage/onboard.dci
/
├── 16
│   ├── normal.dark
│   │   └── 3
│   │       └── 1.webp -> /16/normal.light/3/1.webp
│   └── normal.light
│       └── 3
│           └── 1.webp
└── 24
├── normal.dark
│   └── 3
│       └── 1.webp -> /24/normal.light/3/1.webp
└── normal.light
└── 3
└── 1.webp
...
```
=> feat: dci-icon-theme support multiple icon size

src/util/ddciicon.cpp, tools/dci-icon-theme/main.cpp
https://github.com/linuxdeepin/developer-center/issues/9443
=> Revert "fix: jagged edges on ddciicon"  && dci-icon-theme tweak

include/kernel/dplatformhandle.h
add EffectOut to EffectType
Issue: https://github.com/linuxdeepin/developer-center/issues/10322
=> feat: add window startup effect Type

src/CMakeLists.txt, src/wayland/config.tests/wayland_test/CMakeLists.txt, src/wayland/config.tests/wayland_test/main.cpp, src/wayland/personalizationwaylandclientextension.cpp, src/wayland/personalizationwaylandclientextension.h
Add compile test for treeland
Log:
=> feat: Add compile test

src/CMakeLists.txt, src/wayland/config.tests/wayland_test/CMakeLists.txt
As title
Log: https://pms.uniontech.com/task-view-365811.html
=> chore: Correct the name of TreelandProtocols package in cmake

src/wayland/personalizationwaylandclientextension.cpp, src/wayland/personalizationwaylandclientextension.h
The same application only called the protocol once before
https://pms.uniontech.com/task-view-365811.html
=> fix: Under treeland, the dialog has not disabled titlebar

include/kernel/dguiapplicationhelper.h, src/kernel/dguiapplicationhelper.cpp, src/kernel/dplatformhandle.cpp
only test platformName == wayland
=> chore: add IsWaylandPlatform attribute

src/kernel/dguiapplicationhelper.cpp
remove the operation that reduces lightness of active color in dark theme
Log:
=> chore: highlight color is inconsistency

include/kernel/dplatformtheme.h, src/kernel/dguiapplicationhelper.cpp, src/kernel/dplatformtheme.cpp
get the active color according to system theme(light or dark). 
There are two different active colors between light and dark theme.
Log:
=> chore: add the ActiveColorDark setting

src/kernel/dplatformhandle.cpp, src/wayland/personalizationwaylandclientextension.cpp, src/wayland/personalizationwaylandclientextension.h
Determine whether the protocol is registered
Bug:
=> fix: No judgment on the validity of the protocol

src/kernel/dplatformhandle.cpp
Add the logic about moving the window from platform plugin
Log: as title .
pms: BUG-284215
=> fix: can't drag scrollbar in window under treeland

src/plugins/platform/treeland/personalizationwaylandclientextension.cpp
防止字体出现过大和过小的情况
pms: 368711
https://github.com/linuxdeepin/dde-control-center/pull/1831
=> feat: Limit maximum and minimum fonts

src/plugins/platform/xcb/dxcbplatformwindowinterface.cpp
The default value is 12
pms: BUG-286881
=> chore: update default window corner size

src/util/private/dbuiltiniconengine.cpp
iconSize doesn't multiplied by devicePixelRatio in pixmap,
but it's doesn't need to be in qt5.
pms:BUG-302919
=> fix: icon is blurry

src/kernel/dguiapplicationhelper.cpp
Enhance setSingleInstance to support multiple PID namespaces for
containerized environments. This prevents applications in different
containers from interfering with each other's single instance detection.
The lockfile format becomes: {original_name}_{namespace_inode}.lock,
ensuring unique identification across different PID namespaces.
=> feat: add pid namespace isolation to setSingleInstance

src/kernel/dguiapplicationhelper.cpp
Replace stat-based PID namespace detection with QFileInfo approach for better compatibility across different kernel versions and containerized environments. Add robust parsing and fallback handling for namespace format variations.
PMS: BUG-329663
=> fix: improve PID namespace detection in setSingleInstance
