linuxdeepin/dtkgui

- src/dplatformhandle.cpp
- src/dplatformtheme.cpp
A call to `FETCH_PROPERTY("DTK/WindowRadius", windowRadius)` will return -1 by default, resulting in the right angle parameter. So the cup is fixed here.
Log:
> fix: Fix default display right angle

- src/dplatformhandle.cpp
The result is not as expected, not aesthetically pleasing, so it needs to be left alone.
Log:
> fix: Fix DToolTip control, also modified to rounded corner values.

- .packit.yaml
- rpm/dtkgui.spec
This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> feat: Initial packit setup

- rpm/dtkgui.spec
Fedora no longer installs make in the default build environment.
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> fix: rpm BuildRequires make

- src/src.pro
Use detected pkg-config to fix cross-build in Debian.
Debian Bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979451
> Use detected pkg-config to fix cross build.

- src/kernel/dguiapplicationhelper.cpp
reverts commit 88e0b51da793d3d8b9d48c8515ddf1bf71814860
去掉原来通过共享内存记录pid的方式来避免快速启动应用导致单进程失败的实现
改成启动时通过QLockFile来确保是 server 还是 client。保证只有一个 server ，其他
都是 client （旧逻辑：启动先通过localsocket连接 localserver，连接失败再启动
server，正常启动时没有问题， 当脚本快速多次启动(detached)单进程应用时，都在
等待连接，超时之后就启动了多个应用）
Log: 
Bug: https://pms.uniontech.com/bug-view-111699.html
Influence: single-instance
Change-Id: I9b38e039abbbd70de969a1abf2f4f37fe07e1315
> fix: 修复异常退出时再次启动失败的问题

- src/kernel/dguiapplicationhelper.cpp
修改深色模式下TextWarning的色值为E43F2E
Log:
Task: https://pms.uniontech.com/task-view-138099.html
Influence: 深色模式TextWarning调色板
> fix: 修改深色模式下TextWarning的色值

- debian/rules
build failed when the .git folder exist
Log: fix build failed when the .git folder exist
Resolve: https://github.com/linuxdeepin/developer-center/issues/3328
> fix: build failed when the .git folder exist

- src/util/ddciicon.cpp
- src/util/ddciicon.h
After registering the DciIcon as a meta type, it is
convenient for applications to use it on QVariant.
The << and >> operators are provided to facilitate
applications to read and write.
Log:
Influence: None
Change-Id: I0df76a9e5378a46dcb075b2368fd05eb360d074d
> feat: Register the DciIcon as a meta type

- src/util/ddciicon.cpp
Register the stream operators when the ddciicon
has been initialized. It is convenient to drag
and drop in the list view and register it into
the meta object.
Log:
Influence: None
Change-Id: I90ba9199bd3139e0423f1a3d8a6897990e697708
> chore: Add stream operators for DciIcon

- src/util/private/xdgiconproxyengine.cpp
The return value is not processed effectively, resulting
in an exception under release mode.
Log:
Change-Id: I0c6e918a99fd6f28a441c23a28c786dac572f5e2
> fix: XdgIcon crashed in release mode

- tests/CMakeLists.txt
编译器的compile参数忘记加了,所以单元测试没有生产gcda文件.是个错误
> fix(coverage): add the option of compiler to generage gcda files

- CMakeLists.txt
- archlinux/PKGBUILD
一开始只处理了archlinux和debian,但是nixos更加特殊,以外还有很多不知道的处理,所以让打包者自定义好了
Log: mkspecs path
> chore(mkspecs): define mkspecs self

- .reuse/dep5
- docs/src/dguiapplicationhelper.zh_CN.dox
- src/kernel/dguiapplicationhelper.cpp
- src/private/dguiapplicationhelper_p.h
更新与 DGuiApplicationHelper 相关的文档
相关反馈：https://github.com/orgs/linuxdeepin/discussions/3412
这个 PR 新增了关于两个已有信号的简要说明文档，将原本的私有类标记了 private，也修正了一些 doxygen 不兼容原有 qdoc 的枚举标记的渲染问题。
原有接口的文档并未直接移到外部的 dox 文件中，仅新增的接口文档在 dox 文件中进行了声明。
cc @Wing-summer
> docs: update docs related to DGuiApplicationHelper

- src/kernel/dplatformtheme.cpp
QMetaMethod::invoke will test whether object is an instance
of the QMetaObject as Q_ASSERT(mobj->cast(object)), but invokeOnGadge will not, and their role seem to be the same, we only use DirectConnection to invoke it.
DPlatformTheme is inherits DNativeSettings, and it's metaobject
is changed to DNativeSettings in qt5platform-plugin.
Log: 调用invoke会做assert判断，导致当qt为debug编译时，改变主题会导致程序崩溃
Influence: 当qt为debug编译时，改变主题会导致程序崩溃
Change-Id: I9133430ba6f3df4c4a806ff9fa96ba8ec8213ce4
> fix: Cast error when platform theme changed

- src/kernel/dguiapplicationhelper.cpp
- src/private/dguiapplicationhelper_p.h
DPlatformTheme is invalid when DGuiApplicationHelper::instance()
is called before QApplication constructed. it causes application theme can't follow change by control-center setted.
for example:
```c++
DGuiApplicationHelper::instance();
QApplication a(argc, argv);
```
it also reports warning info about `Must construct a QGuiApplication
before accessing a platform function` in QGuiApplication.
Log: 延迟DPlantfromTheme构造
Bug: https://pms.uniontech.com/bug-view-160485.html 
Influence: 先调用DGuiApplicationHelper::instance()可能有影响， 若先构造QApplication，与之前逻辑一致
Change-Id: I91297fb47c38c1ebb6d97f9c62915aa5d5557624
> fix: Application theme can't follow change by system

- src/filedrag/dfiledragserver.cpp
qApp->applicationPid() 获取的是沙箱中的pid
QDBusConnectionInterface::servicePid 获取的是沙箱外的pid
改成相同的pid
Log: 修复v23无法拖拽邮件到桌面
Bug: https://pms.uniontech.com/bug-view-156601.html
Change-Id: I1e41a47e7f1e5030a33fff766b7fa35c675b7ae7
> fix: filedrag do not send data in ll-box

- src/util/ddciicon.cpp
it causes paint error when load unsupport image format, we add
output some information.
we can install package `qt5-image-formats-plugins`.
it's need to support `webp` image for some dci icon.
Log: 添加dciicon图标解析失败导致无法绘制时的警告信息
Change-Id: Ief27263af5caa74c4a9f0436ebdf8759ea39bd82
> feat: Add Warning for unsupport Image format

- include/kernel/dguiapplicationhelper.h
- src/kernel/dguiapplicationhelper.cpp
moving implement of loadTranslator from dtkwidget,
refact the code's logic.
Log: 加载翻译功能移至dtkgui，以便供dtkdeclarative使用
Bug: https://pms.uniontech.com/bug-view-157977.html
Influence: qml相关应用没有加载翻译
Change-Id: I75483320cbb6f8a1378cb8a93f00da3d8abfc26f
> feat: Moving loadTranslator from dtkwidget

- src/util/dsvgrenderer.cpp
librsvg2 对 SVG2 的 href 解析有问题，需要改成 xlink:href 规避
当前是临时规避方案，如果后续 librsvg2 升级修复这个问题，可以 revert
https://www.w3.org/TR/2018/CR-SVG2-20181004/types.html#InterfaceSVGURIReference
Task: https://pms.uniontech.com/task-view-218689.html
Influence: 包含href的svg图标
Log: 修复包含href的svg图标无法显示的问题
Change-Id: Idaf0ca9519153cd8fe217aeaaeab250b18f35393
> fix: 包含 href 特性的 svg 图标无法显示

- CMakeLists.txt
Removing asan check
Log: 移除库的asan检测
Change-Id: I248ae4d41dfcb70e565fc68d510b9c318c459ee1
> fix: Remove ASan check for debug

- src/util/ddciicon.cpp
uengine app not set appname cause DSGApplication::id() assert
Log: none
Influence: uengine app
> fix: uengine not set appname cause crashed

- misc/DtkGuiConfig.cmake.in
DtkGuiConfig.cmake will always find the library under system library path. This will cause a linking error when you want to use the version deployed by yourself. Fix that by appending the path prefix.
Log: fix DtkGuiConfig.cmake.in
Influence: DtkGuiConfig.cmake.in
> chore: fix linking error

- src/dbus/xeventmonitor_interface.cpp
- src/dbus/xeventmonitor_interface.h
qRegisterMetaType<AreaList>("AreaList");
覆盖导致dock使用接口出现位置异常
https://github.com/linuxdeepin/dde-qt-dbus-factory/blob/cc2a09558b78be6a975e4c1fff38bc4eaa814a59/libdframeworkdbus/types/arealist.cpp#L35
Bug: https://pms.uniontech.com/bug-view-175747.html
Log: none
Influence: dock hide and show
Change-Id: Ie10bd436ddaa66e0477b5db40d6e36fbea2d0733
> fix: AreadList metaType override

- src/util/icons/deepin-theme-plugin-icons.qrc
- src/util/icons/icons/dark/edit-clear_active_30px.svg
- src/util/icons/icons/light/edit-clear_active_30px.svg
QLineEditIconButton(Qt 5.15) get pixmap from Active state instead of Selected state when button is down
add active state pixmap (note that dstyle  will fill 10% opacity black or white on active state)
Bug: https://pms.uniontech.com/bug-view-172425.html
Incluence: QLineEdit clearbutton
Log: none
Change-Id: I182e6ec7b68bd251a3eb935616d2e3f6393d6676
> fix: edit clearbutton pressed style incorrect

- tools/dci-icon-theme/README.md
- tools/dci-icon-theme/main.cpp
--fix-dark-theme only copy linktarget file to ouputput dir. record link-target map and makelink after fix job
update version to 0.0.2
Log: none
Change-Id: I9100c98107551eb002656e34937a8524075743bc
> fix: fix-dark-theme not work on link file

- docs/src/dguiapplicationhelper.zh_CN.dox
- docs/src/dplatformtheme.zh_CN.dox
- include/kernel/dguiapplicationhelper.h
- include/kernel/dplatformtheme.h
- src/kernel/dguiapplicationhelper.cpp
- src/kernel/dplatformtheme.cpp
- src/private/dguiapplicationhelper_p.h
enable SizeMode support by default.
user can set environment `D_DTK_SIZEMODE` to set
SizeMode support.
application can set SizeMode by `setSizeMode` explicitly.
Log: 支持紧凑模式切换
Task: https://pms.uniontech.com/task-view-227385.html
Change-Id: I2eefe254f9bbf380d9ab133c4eb0caa979ed1356
> feat: Add SizeMode support

- tests/CMakeLists.txt
Change GTest::gtest to GTest::GTest for backward compatibility.
Log: change GTest::gtest to GTest::GTest
> chore: change GTest::gtest for compatibility

- include/kernel/dplatformtheme.h
- src/kernel/dplatformtheme.cpp
same as Qt::ScrollBarPolicy
0 show as needed auto hide, default
1 always off
2 always on
Task: https://pms.uniontech.com/task-view-240117.html
Log: scrollbar policy
Change-Id: Ia37f2a5661cb27de568bc3f7ece5a4a6a1fcae97
> feat: add scrollBarPolicy interface

- src/CMakeLists.txt
do not use PkgConfig::libraw
cmake 3.16 changelog
If a full path to the found library can't be determined, but it's still visible to the linker, pass it through as ``-l<name>``.  Previous versions of CMake failed in this case.
Log: build
Change-Id: I48a03142a0f4778a531e5138ea7489a8f42ce5c5
> fix(build): build failed when cmake < 3.16

- src/util/ddciicon.cpp
- tests/src/ut_ddciicon.cpp
qreal pixmapScale = 48 / 256; // 0
qreal pixmapScale = qreal(48) / 256; // 0.1875
Log: dci image size calculation error
> fix: dci icon image scale calculation error

- docs/util/dicontheme.zh_CN.dox
- include/util/dicontheme.h
- src/util/dicontheme.cpp
- src/util/util.cmake
DIconTheme::createIconEngine for qt5integration
1. try createBuiltinIconEngine first
2. try createXdgProxyIconEngine or fallback to fromTheme 
Warning : do not call from qplatformTheme createIconEngine without DontFallbackToQIconFromTheme flag
Log: add createIconEngine
> feat: add DIconTheme::createIconEngine

- src/kernel/dguiapplicationhelper.cpp
- src/private/dguiapplicationhelper_p.h
在 setApplicationName 前调用 dconfig 会导致 appid 不匹配
导致无法正确读取修改配置.
没有 setApplicationName 时 applicationName 会 fallback 到二进制的名字( argv[0] )
将 docnfig 初始化改到第一次调用 themeType() 中
Issue: https://github.com/linuxdeepin/developer-center/issues/4117
> fix: dconfig get appid error

- src/kernel/dguiapplicationhelper.cpp
When we call setThemeType to DarkType, it will sync DConfig's
themeType, and reset it to UnknowType, and it cause ut failed.
> fix: Inconsistent themeType when setThemeType

- src/kernel/dguiapplicationhelper.cpp
- tests/main.cpp
ASSERT: "The application ID is empty" if `setPaletteType` is
called before QGuiApplication contrusted.
`q->themeType` will try to use `DConfig`, It's applicationName
is Empty.
> fix: App crashed when `setPaletteType` called early

- src/kernel/dguiapplicationhelper.cpp
- src/private/dguiapplicationhelper_p.h
We should emit Event to prompt QGuiApplication update QPalette.
if themeType is changed firstly.
> fix: ThemeType is inconsistent

- CMakeLists.txt
Log:
Never modify the value of CMAKE_INSTALL_PREFIX after including GNUInstallDirs， Otherwise incorrect CMAKE_INSTALL_FULL_XXXX values will be computed
> fix: must set CMAKE_INSTALL_PREFIX before GNUInstallDirs

- src/kernel/dguiapplicationhelper.cpp
Maunal dbus service isn't registed in live system firstly, we
should wakeup it instead of blocking UI.
It may be cause app of `longlong` hasn't Manual when click menu
to show Maunal firstly.
Bug: https://pms.uniontech.com/bug-view-197713/.html
Log: 解决在live系统中，帮助手册dbus调用导致应用阻塞
> fix: App blocked by hasUserManual in live system

- .gitignore
chore: ignore doxygen-theme folder
Log: 修复编译时加上BUILD_THEME宏后，自动拉取doxygen-theme导致git管理的项目产生污染
Task: https://github.com/linuxdeepin/dtk/issues/99
> chore: ignore doxygen-theme folder

- dtkgui.cmake
change OUTPUT_DIR to CMAKE_CURRENT_BINARY_DIR
Log: change OUTPUT_DIR to CMAKE_CURRENT_BINARY_DIR
> chore: change OUTPUT_DIR variable in cmake

- include/kernel/dplatformtheme.h
It exports to qt meta system for qml.
and it doesn't break ABI compatibility depend on
https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B#Using_signals_instead_of_virtual_functions
> refactor: Move dotsPerInch from normal function to slots

- src/util/dicontheme.cpp
- src/util/private/diconproxyengine.cpp
- src/util/private/diconproxyengine_p.h
DIconTheme::createIconEngine always create DIconProxyEngine so DIconTheme::isBuiltinIcon && DIconTheme::isXdgIcon failed add DIconProxyEngine::proxyKey() to get proxy iconengine's key
> fix(build): DIconTheme ut failed 

- src/filedrag/dfiledragclient.cpp
- src/filedrag/dfiledragserver.cpp
- tests/CMakeLists.txt
- tests/src/ut_dfiledrag.cpp
- emit serverDestroyed in ~DFileDragServer()
- DDndClientSignalRelay::serverDestroyed emit DFileDragClient::serverDestroyed
- add dfiledrag unit test
> fix: DFileDragClient::serverDestroyed nerver emit

- src/kernel/dplatformtheme.cpp
> fix: dplatformtheme fetchPalette crash

- include/util/dfontmanager.h
- src/util/private/dbuiltiniconengine.cpp
QThemeIconEntries changed from QList<QIconLoaderEngineEntry*>
to std::vector<std::unique_ptr<QIconLoaderEngineEntry>>
QFont hasn't include QObject header file.
> fix: Compiling error in qt6.4

- src/util/private/dciiconengine.cpp
dci 图标缓存没有加上主题名导致可能在不同的主题时匹配到其他主题缓存的图标
Issue: https://github.com/linuxdeepin/developer-center/issues/4517
> fix: dci icon cache key miss theme name

- src/kernel/dguiapplicationhelper.cpp
修改为设置后立即保存
Log: 修复应用异常退出后颜色主题未保存的问题
Influence: 应用的主题选项在退出重启后未恢复上一次的选择
Bug: https://pms.uniontech.com/bug-view-201203.html
Change-Id: I73b92fd781737e757827bbb6aca87887c2c16ce9
> fix: 修复应用异常退出后颜色主题未保存的问题

- src/kernel/dguiapplicationhelper.cpp
TextLively is different between light and dark theme, otherwise
it can't see clearly in light theme.
> fix: Wrong value of DPalette::TextLively

- debian/control
- docs/CMakeLists.txt
depends qttools5-dev or qt6-tools-dev
add Build-Profiles to ignore package build
(dpkg-buildpackage --build-profiles=nodoc)
> chore: find qhelpgenerator from property

- archlinux/PKGBUILD
- src/util/dsvgrenderer.cpp
- src/util/private/xdgiconproxyengine.cpp
Svg filters attribute are not supported by QSvgRenderer, and it will not be. see https://bugreports.qt.io/browse/QTBUG-9081
XdgIconLoaderEngine(>3.6) use QSvgRenderer to render svg instead of svg icon engines https://github.com/lxqt/libqtxdg/blob/master/src/xdgiconloader/xdgiconloader.cpp#L814
Archlinux DTK_DISABLE_LIBRSVG=ON by default https://github.com/linuxdeepin/dtkgui/pull/130
- turn off DTK_DISABLE_LIBRSVG option
- force get pixmap from icon engines
- fix DSvgRenderer::toImage return null image with empty elementId on DTK_DISABLE_LIBRSVG
> fix: svg with filter attribute rendering exception

- src/CMakeLists.txt
When disable librsvg, we use QtSvg to implement dsvgrenderer. Link to Qt(5/6)::Svg target.
Log: fix missing link when disable librsvg
> fix: missing link when disable librsvg

- src/util/private/diconproxyengine.cpp
The icon names of `IconEngine` and `DIconProxyEngine` are
inconsistent when there is no such icon.
Issue: https://github.com/linuxdeepin/developer-center/issues/5760
> fix: Wrong IconName for DIconEngine

- include/util/ddciicon.h
ddciicon.h does not explicitly include QSharedPointer, leading to
incomplete type. Include QSharedPointer explicitly.
Log: fix indirect inclusion of QSharedPointer
> fix: indirect inclusion of QSharedPointer

- docs/util/ddesktopservices.h.zh_CN.dox
- include/DtkGui/DDesktopServices
- include/util/ddesktopservices.h
- src/util/ddesktopservices_linux.cpp
- move ddesktopservices from dtkwidget to dtkgui
- add docs for ddesktopservice
- showFileItemPropertie ==> showFileItemProperty
- use dbus to check SoundEffect.Enabled instead of Gsettings
Issue: https://github.com/linuxdeepin/dtk/issues/134
> feat: move ddesktopservices to dtkgui

- src/util/private/diconproxyengine.cpp
fallback to QIconLoaderEngine on DTK_DISABLE_LIBXDG
Issue: https://github.com/linuxdeepin/developer-center/issues/6459
> fix: xdg icon loading failed with qt6

- debian/control
invalid-profile-name-in-build-profiles-field nobin (in section for libdtkgui5-bin)
> fix: debian build failed

- src/util/dicontheme.cpp
Adding icon's themeName as a part of the cache key.
> fix: icon doesn't update when iconTheme changed

- src/kernel/dguiapplicationhelper.cpp
- src/private/dguiapplicationhelper_p.h
`fontChanged` has been deprecated in qt6, and the signal can't
be emitted in `qdeepin` when font changed.
> fix: font can't follow changes in qt6

- src/kernel/dguiapplicationhelper.cpp
We only save config's value when caller update paletteType manually.
> fix: changed paletteType's config value

- src/util/private/diconproxyengine.cpp
- src/util/private/diconproxyengine_p.h
We should call proxy's `availableSizes` function.
`availableSizes` always return empty list for icons, it causes
`QPainter::begin: Paint device returned engine == 0` when painting
to QImage.
> fix: wrong availableSizes for DIconProxyEngine 

- src/kernel/dguiapplicationhelper.cpp
原来 continue 只是不用 QColor()/黑色 覆盖
去掉 continue 才是使用 DPalette 中的 PlaceholderText 覆盖..
Issue: https://github.com/linuxdeepin/developer-center/issues/7554
> fix: PlaceholderText color tweak

- src/kernel/dplatformhandle.cpp
`*(reinterpret_cast<const QVector<qint32>*>(&area)` is not equal
QVector<qint32> in qt6, it cause QVariant's equal function is
invalid. so we perform type conversion explicitly.
> fix: setWindowBlurAreaByWM only work once in qt6

- src/kernel/dguiapplicationhelper.cpp
We should update baseFont from qGuiApp not just when font changed.
Issue: https://github.com/linuxdeepin/developer-center/issues/8040
> fix: missing initialization for baseFont of fontManager

- src/util/private/diconproxyengine.cpp
- 不需要考虑 DontFallbackToQIconFromTheme 这里是直接 new QIconLoaderEngine
- qErrnoWarning ==> qWarning 不需要 lasterror
Issue: https://github.com/linuxdeepin/developer-center/issues/8436, https://github.com/linuxdeepin/developer-center/issues/8241
> fix: create icon engine faild on Qt6

- src/util/ddciicon.cpp
Use smooth scaling before drawing to smaller QImage
Issue: https://github.com/linuxdeepin/developer-center/issues/8691
> fix: jagged edges on ddciicon

- examples/animation-dci/main.cpp
- src/util/ddciiconplayer.cpp
-  animation-dci supports custom icon 
open or drop a dci icon on label to display dci icon
> chore: animation-dci supports custom icon

- include/kernel/dplatformhandle.h
- src/kernel/dplatformhandle.cpp
(cherry picked from commit 4f4be15cb48788a233f855c80bd15619d266fcd9)
(cherry picked from commit 762bd7b2eced343921346b37d673bbb7f536592d)
Bug: https://pms.uniontech.com/bug-view-244347.html
https://pms.uniontech.com/bug-view-243363.html
https://pms.uniontech.com/bug-view-240437.html
> feat: support to change window effects

- src/kernel/dplatformhandle.cpp
Missing check for Treeland.
TODO: CreatorWindowEventFile should distinguish between X11 and
Treeland.
> fix: app crashed in x11

- src/util/private/dbuiltiniconengine.cpp
- tests/src/ut_builtinengine.cpp
> feat: Support Qt 6.8

- include/kernel/dguiapplicationhelper.h
- src/kernel/dguiapplicationhelper.cpp
set/unset `D_DTK_DISABLE_ANIMATIONS` according to the dconfig
required: https://github.com/linuxdeepin/dtkcommon/pull/79
> chore: config dtk animations

- src/kernel/dguiapplicationhelper.cpp
Avoid printing such logs to terminal
Bug: https://pms.uniontech.com/bug-view-284539.html
Log: Print "load translate" debug log to channels
> fix: Print "load translate" debug log to channels

- src/kernel/dplatformhandle.cpp
- src/wayland/personalizationwaylandclientextension.cpp
- src/wayland/personalizationwaylandclientextension.h
pms:
BUG-278197
BUG-278281
BUG-284681
Log: Supporting window blury effect under Treeland
> fix: Supporting window blury effect under Treeland

- src/kernel/dplatformhandle.cpp
…ter references
as title
pms: Task-368711
>  fix: Possible null pointer dereference and Notitlebar input parameter error

- src/kernel/dwindowmanagerhelper.cpp
- src/plugins/platform/treeland/dtreelandwindowmanagerhelper.cpp
- src/plugins/platform/treeland/dtreelandwindowmanagerhelper.h
WindowManager's some interface may be deprecated, like MotifFunctions
and allWindowIdList.
and there is currently no abstraction of platform common
interfaces.
pms: BUG-287901
> feat: support treeland platform for wmHelper

- src/plugins/platform/treeland/dtreelandplatformwindowinterface.cpp
waylandWindow is empty when sometimes.
App crashed when window visibleChanged repeated.
pms: BUG-278281
> fix: blur is invalid for treeland

- src/plugins/platform/treeland/dtreelandplatformwindowinterface.cpp
> fix: app crashed when window destroyed in quick

- src/kernel/dguiapplicationhelper.cpp
qt translations fallback to GenericDataLocation paths
> fix: linglong app load qt translations failed

- src/plugins/platform/treeland/dtreelandplatformwindowinterface.cpp
- src/plugins/platform/treeland/dtreelandplatformwindowinterface.h
Set blur again when creating the surface
pms: BUG-278281
> fix: window blur invalid

- src/plugins/platform/treeland/dtreelandplatformwindowinterface.cpp
add nullptr check
pms: Bug-289175
> fix: nullptr check missing

- src/util/private/dbuiltiniconengine.cpp
- src/util/private/dbuiltiniconengine_p.h
- src/util/private/dciiconengine.cpp
- src/util/private/dciiconengine_p.h
Qt6 QIconEngine::availableSizes will not call
virtual_hook(QIconEngine::AvailableSizesHook
> fix: availableSizes not work on Qt6

- src/plugins/dplatforminterface.cpp
> fix: missing default windowRadius

- src/kernel/dplatformhandle.cpp
- src/plugins/dplatformwindowinterface.cpp
- src/plugins/platform/treeland/dtreelandplatformwindowinterface.cpp
- src/plugins/platform/treeland/dtreelandplatformwindowinterface.h
- src/plugins/platform/xcb/dxcbplatformwindowinterface.cpp
- src/plugins/platform/xcb/dxcbplatformwindowinterface.h
- src/private/dplatformwindowinterface_p.h
- src/private/private.cmake
Refact DPlatformHandle to update window settings.
Remove task dequeue in treeland interface when Personalization is inactive.
Add DTreeLandPlatformWindowHelper to manage windowContext.
pms: TASK-368399
> refact: refacting DPlatformHandle to adapt treeland

- src/util/ddciicon.cpp
> fix: iterator out of bounds for dciicon

- src/util/dfontmanager.cpp
FamilyResolved flag not set
pms: BUG-295665
> fix: set font family invalid

- src/plugins/platform/treeland/dtreelandplatformwindowinterface.cpp
qobject_cast<QWindow*>(window) is returned nullptr if window is destroyed in qt6, and we can see it  on tst_QWindow::qobject_castOnDestruction() in tst_qwindow.cpp.
Object's address may be the same as before  in qt6,  memory may be optimized.
pms: BUG-299239
> fix: accessing wild pointer in qt6

- docs/util/ddciicon.zh_CN.dox
- include/util/ddciicon.h
- src/util/ddciicon.cpp
Renaming enum would break ABI, but using doesn't modify ABI.
pms: BUG-368399
> chore: correct typos about Dtk::Gui::DDciIcon::IconAttribute

- src/plugins/platform/treeland/dtreelandplatformwindowinterface.cpp
- src/plugins/platform/treeland/dtreelandplatformwindowinterface.h
It's exist when using DPlatformHandle is stack variable.
We save window decoration state in DTreeLandPlatformWindowHelper, and refresh them when surface created.
pms: BUG-278281
> fix: missing window decoration for treeland

- src/kernel/dguiapplicationhelper.cpp
Changed Q_GLOBAL_STATIC to Q_GLOBAL_STATIC_WITH_ARGS for
OrgDeepinDTKPreference initialization
This modification provides better type safety and clearer syntax for the
complex initialization parameters
The change maintains the same functionality while following Qt's
recommended practices for static initialization
refactor: 更新 DConfig 初始化语法
将 Q_GLOBAL_STATIC 改为 Q_GLOBAL_STATIC_WITH_ARGS 用于
OrgDeepinDTKPreference 初始化
此修改为复杂的初始化参数提供了更好的类型安全性和更清晰的语法
该变更保持了相同的功能，同时遵循 Qt 推荐的静态初始化实践
> fix: build failed in qt5

- include/kernel/dguiapplicationhelper.h
- src/kernel/dguiapplicationhelper.cpp
使用另一个 `QTranslator::load()` 重载来使代码更简洁,并潜在的支持 `QLocale::uiLanguages()`.
> chore: use another QTranslator::load overload to tidy code

- tools/dci-icon-theme/CMakeLists.txt
- tools/dci-icon-theme/main.cpp
1. Changed from QCoreApplication to QGuiApplication to support SVG rendering
2. Updated CMakeLists to link against QtGui instead of QtCore
3. This change is necessary because SVG rendering requires GUI components
4. Note: CLI environment users must set QT_QPA_PLATFORM=offscreen
feat: 切换到 QGuiApplication 以支持 SVG 渲染
1. 从 QCoreApplication 切换到 QGuiApplication 以支持 SVG 渲染
2. 更新 CMakeLists 链接 QtGui 替代 QtCore
3. 此变更是必要的因为 SVG 渲染需要 GUI 组件
4. 注意：命令行环境用户需要设置 QT_QPA_PLATFORM=offscreen
> feat: switch to QGuiApplication for SVG rendering

- docs/util/ddciiconplayer.zh_CN.dox
- include/util/ddciiconplayer.h
- src/util/ddciiconplayer.cpp
1. Added new overloaded play method that accepts
DDciIconImagePlayer::Flags parameter
2. Modified existing play method to call new method with default
IgnoreLastImageLoop flag
3. Updated documentation to reflect new method signature and behavior
4. Allows more control over icon playback behavior through flags
parameter
feat: 为 DDciIconPlayer 的 play 方法添加 flags 参数
1. 添加了新的重载 play 方法，接受 DDciIconImagePlayer::Flags 参数
2. 修改现有 play 方法以使用默认的 IgnoreLastImageLoop 标志调用新方法
3. 更新文档以反映新的方法签名和行为
4. 通过 flags 参数提供对图标播放行为的更多控制
> feat: add flags parameter to DDciIconPlayer play method

- include/util/dfontmanager.h
- src/private/dfontmanager_p.h
- src/util/dfontmanager.cpp
- tests/src/ut_dfontmanager.cpp
Added T11 font size with 8px default value to extend the font size options
Modified T5 default size from 17px to 16px for better size progression Updated font pixel size array to include the new T11 size Added t11() accessor method and corresponding test case cherry-pick from: https://github.com/linuxdeepin/dtkwidget/commit/2c3b351b439f56a9373538e8c6b6660167eb378d
feat: 添加 T11 字体大小并调整 T5 默认值
添加了默认值为 8px 的 T11 字体大小以扩展字体大小选项
将 T5 默认大小从 17px 修改为 16px 以获得更好的大小递进
更新了字体像素大小数组以包含新的 T11 大小
添加了 t11() 访问器方法和相应的测试用例
cherry-pick from: https://github.com/linuxdeepin/dtkwidget/commit/2c3b351b439f56a9373538e8c6b6660167eb378d
pms: BUG-310879
> feat: add T11 font size and adjust T5 default

- tests/platform-plugin-test/qminimalintegration.cpp
Qt 6.9 renamed <private/qdesktopunixservices_p.h> to <private/qgenericunixservices_p.h>, as well as some of the classes along the same format (QGenericUnixServices => QDesktopUnixServices).
Add a condition test with QT_VERSION to fix build with Qt >= 6.9.
> fix(tests): fix build for Qt 6.9
